name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - '*'
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build app
        run: ./gradlew assembleRelease -Penable-updater

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: arm64-v8a-${{ github.sha }}
          path: app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk

      - name: Upload Universal APK
        uses: actions/upload-artifact@v4
        with:
          name: universal-${{ github.sha }}
          path: app/build/outputs/apk/release/app-universal-release-unsigned.apk

      - name: Upload mapping
        uses: actions/upload-artifact@v4
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/release

      - name: Set version tag or fallback
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION_TAG=build-${GITHUB_SHA::7}" >> $GITHUB_ENV
          fi

      - name: Sign APKs
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Rename & SHA256 APKs
        run: |
          set -e

          mv app/build/outputs/apk/release/app-universal-release-unsigned-signed.apk aniyomi-${{ env.VERSION_TAG }}.apk
          echo "APK_UNIVERSAL_SHA=$(sha256sum aniyomi-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }')" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned-signed.apk aniyomi-arm64-v8a-${{ env.VERSION_TAG }}.apk
          echo "APK_ARM64_V8A_SHA=$(sha256sum aniyomi-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }')" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned-signed.apk aniyomi-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          echo "APK_ARMEABI_V7A_SHA=$(sha256sum aniyomi-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }')" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-x86-release-unsigned-signed.apk aniyomi-x86-${{ env.VERSION_TAG }}.apk
          echo "APK_X86_SHA=$(sha256sum aniyomi-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }')" >> $GITHUB_ENV

          mv app/build/outputs/apk/release/app-x86_64-release-unsigned-signed.apk aniyomi-x86_64-${{ env.VERSION_TAG }}.apk
          echo "APK_X86_64_SHA=$(sha256sum aniyomi-x86_64-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }')" >> $GITHUB_ENV

      - name: Upload signed APKs
        uses: actions/upload-artifact@v4
        with:
          name: signed-apks-${{ env.VERSION_TAG }}
          path: |
            aniyomi-${{ env.VERSION_TAG }}.apk
            aniyomi-arm64-v8a-${{ env.VERSION_TAG }}.apk
            aniyomi-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            aniyomi-x86-${{ env.VERSION_TAG }}.apk
            aniyomi-x86_64-${{ env.VERSION_TAG }}.apk
